version: 0.{build}

environment:
  QTDIR: C:\Qt\5.9.1\msvc2015

clone_folder: c:\dev\rtide
clone_depth: 5

init:
  - set PATH=C:\msys64;C:\Qt\5.9.1\msvc2015_64\bin;%PATH%

install:
  - git submodule update --init --recursive
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - set make=nmake.exe

before_build:
  - mkdir %APPVEYOR_BUILD_FOLDER%\build
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - qmake ..\src\rtide.pro -r -Wall CONFIG+=release

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - '%make%'

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - 7z a rtide-win64-v0-nodll.zip "%APPVEYOR_BUILD_FOLDER%\*" -xr!build -xr!.git
  - windeployqt.exe "%APPVEYOR_BUILD_FOLDER%\bin"
  - cd '%APPVEYOR_BUILD_FOLDER%'
  - 7z a rtide-win64-v0.zip "%APPVEYOR_BUILD_FOLDER%\*" -xr!build -xr!.git

artifacts:
  - path: rtide-win64-v0-nodll.zip
    name: rtide-nodll
  - path: rtide-win64-v0.zip
    name: rtide

test: off
