image: Visual Studio 2017

version: 0.{build}

environment:
  QTDIR: C:\Qt\5.12.2\msvc2017

clone_folder: c:\dev\udk-ide
clone_depth: 5

init:
  - set PATH=C:\msys64;C:\Qt\5.12.2\msvc2017\bin;%PATH%

install:
  - git submodule update --init --recursive
  - qmake -v
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - set make=nmake.exe

before_build:
  - mkdir %APPVEYOR_BUILD_FOLDER%\build
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - qmake ..\src\udk-ide.pro -r -Wall CONFIG+=release

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - '%make%'

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cp -r contrib\edbee-data\keymaps data\
  - cp -r contrib\edbee-data\syntaxfiles data\
  - 7z a udk-ide-win64-v0-nodll.zip "%APPVEYOR_BUILD_FOLDER%\..\*" -xr!build -xr!.git -xr!src -xr!contrib
  - windeployqt.exe "%APPVEYOR_BUILD_FOLDER%\bin"
  - 7z a udk-ide-win64-v0.zip "%APPVEYOR_BUILD_FOLDER%\..\*" -xr!build -xr!.git -xr!src -xr!contrib -xr!udk-ide*.zip

artifacts:
  - path: udk-ide-win64-v0-nodll.zip
    name: udk-ide-nodll
  - path: udk-ide-win64-v0.zip
    name: udk-ide

test: off
