version: 0.{build}

clone_folder: c:\dev\rtide
clone_depth: 5

image:
  - Visual Studio 2015

init:
  - set PATH=C:\msys64;C:\Qt\5.9.1\msvc2015_64\bin;%PATH%

install:
  - git submodule update --init --recursive

before_build:
  - mkdir %APPVEYOR_BUILD_FOLDER%\build
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - qmake ..\src\rtide.pro -r -Wall CONFIG+=release

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - nmake.exe

test: off
