version: 0.{build}

environment:
  matrix:
    - QTDIR: C:\Qt\5.9.1\mingw53_32
    - QTDIR: C:\Qt\5.9.1\msvc2015

clone_folder: c:\dev\rtide
clone_depth: 5

init:
  - set PATH=C:\msys64;C:\Qt\5.9.1\msvc2015_64\bin;%PATH%

install:
  - git submodule update --init --recursive
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc2013=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2015=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

before_build:
  - mkdir %APPVEYOR_BUILD_FOLDER%\build
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - qmake ..\src\rtide.pro -r -Wall CONFIG+=release

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - '%make%'

test: off
